video: tegra: host: Fix undefined reference to nvhost_syncpt_name
This was left at commit d616fd4eb059930be9a93e468e302b911dcd8aff.

Change-Id: I11b433612ed72fc7eef2276af44762162581a1f6
Signed-off-by: Hiroshi DOYU <hdoyu@nvidia.com>
Reviewed-on: http://git-master/r/64051
Reviewed-by: Varun Colbert <vcolbert@nvidia.com>
Tested-by: Varun Colbert <vcolbert@nvidia.com>